{
 "title": "Vertica Database",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Agent status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host $tag_agent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "agent" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "agent_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "agent" ], "type": "tag" }
     ],
     "measurement": "agent_status",
     "query": "SELECT \"host\", \"agent\", \"status\", \"error\" FROM \"agent_status\" WHERE (\"status\" != 100) AND $timeFilter",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "!=", "value": "100" }
     ]
    }
   ]
  },
  { "title": "Database metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nodes Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "database",
     "query": "SELECT last(\"node_state\") FROM \"database\" WHERE $timeFilter GROUP BY \"node_name\"",
     "select": [
      [
       { "params": [ "node_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries errors count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errors count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "database_history",
     "select": [
      [
       { "params": [ "error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries per label",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Request: $tag_request_label",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "request_label" ], "type": "tag" }
     ],
     "measurement": "database_history",
     "query": "SELECT mean(\"point_value\") FROM \"database_history\" WHERE (\"request_label\" != 'PERFORMANCE_AGENT' AND (\"request_duration_ms\" > 100 OR \"is_executing\" = true)) AND $timeFilter GROUP BY time(1m), \"request_label\"",
     "select": [
      [
       { "params": [ "point_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request_label", "operator": "!=", "value": "PERFORMANCE_AGENT" },
      { "condition": "AND", "key": "request_duration_ms", "operator": ">", "value": "100" },
      { "condition": "OR", "key": "is_executing", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Queries by Transaction ID",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_request_label ($tag_transaction_id | $tag_request_id)",
     "groupBy": [
      { "params": [ "1ms" ], "type": "time" },
      { "params": [ "transaction_id" ], "type": "tag" },
      { "params": [ "request_label" ], "type": "tag" },
      { "params": [ "request_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "database_history",
     "query": "SELECT count(\"point_type\") FROM \"database_history\" WHERE (\"request_label\" != 'PERFORMANCE_AGENT' AND ((\"is_executing\"=true AND \"request_duration_ms\" = 0)  OR \"request_duration_ms\" > 100)) AND $timeFilter GROUP BY time(1ms), \"transaction_id\", \"request_label\", \"request_id\" fill(none)",
     "select": [
      [
       { "params": [ "point_type" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "request_label", "operator": "!=", "value": "PERFORMANCE_AGENT" },
      { "condition": "AND", "key": "request_duration_ms", "operator": ">", "value": "100" },
      { "condition": "OR", "key": "is_executing", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Queries History",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "measurement": "database_history",
     "query": "SELECT \"transaction_id\", \"request_id\", \"request\", \"request_label\", \"request_duration_ms\",\"success\", \"is_executing\", \"error_count\" FROM \"database_history\" WHERE (\"point_type\" = 'start' AND \"request_label\" != 'PERFORMANCE_AGENT' AND ((\"is_executing\"=true  AND \"request_duration_ms\" = 0)  OR \"request_duration_ms\" > 100)) AND $timeFilter",
     "select": [
      [
       { "params": [ "transaction_id" ], "type": "field" }
      ],
      [
       { "params": [ "request_id" ], "type": "field" }
      ],
      [
       { "params": [ "request" ], "type": "field" }
      ],
      [
       { "params": [ "request_label" ], "type": "field" }
      ],
      [
       { "params": [ "request_duration_ms" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "is_executing" ], "type": "field" }
      ],
      [
       { "params": [ "error_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "point_type", "operator": "=", "value": "start" },
      { "condition": "AND", "key": "request_label", "operator": "!=", "value": "PERFORMANCE_AGENT" },
      { "condition": "AND", "key": "request_duration_ms", "operator": ">", "value": "100" }
     ]
    }
   ]
  },
  {
   "title": "Сluster request distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host | $tag_node_name",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}