{
 "title": "Hardware and network",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Agent status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host $tag_agent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "agent" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "agent_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "agent" ], "type": "tag" }
     ],
     "measurement": "agent_status",
     "query": "SELECT \"host\", \"agent\", \"status\", \"error\" FROM \"agent_status\" WHERE (\"status\" != 100) AND $timeFilter",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "!=", "value": "100" }
     ]
    }
   ]
  },
  { "title": "Hardware metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host (host full process)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100*count(\"idle\")-sum(\"idle\")  FROM \"cpu\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "I/O requests ($tag_host $tag_disk)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "%util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ram",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ram",
     "select": [
      [
       { "params": [ "swpd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "I/O (r/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "r_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "I/O (w/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "w_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "rkB_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "wkB_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Average Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Svctm",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "svctm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read Average Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "r_await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write Average Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "w_await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "avgqu-sz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "avgqu-sz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Received / Send data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Received" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Send" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received / Send packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Received packets" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Send packets" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received / Send errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_errs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Receive errors" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_errs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Send errors" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received / Send Dropped packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_drop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Received dropped packets" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_drop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Send dropped packets" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}