{
 "title": "{{ item.value.dbname }}",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Agent status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host $tag_agent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "agent" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "agent_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "agent" ], "type": "tag" }
     ],
     "measurement": "agent_status",
     "query": "SELECT \"host\", \"agent\", \"status\", \"error\" FROM \"agent_status\" WHERE (\"status\" != 100) AND $timeFilter",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "!=", "value": "100" }
     ]
    }
   ]
  },
  { "title": "Hardware metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Process Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "process",
     "query": "SELECT last(*) FROM \"process\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host (host full process)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100*count(\"idle\")-sum(\"idle\")  FROM \"cpu\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "VerticaDB ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process",
     "select": [
      [
       { "params": [ "CPU" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "I/O requests ($tag_host $tag_disk)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "%util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ram",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ram",
     "select": [
      [
       { "params": [ "swpd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "I/O (r/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "r_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "I/O (w/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "w_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "rkB_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "wkB_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Average Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Svctm",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "svctm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read Average Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "r_await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write Average Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "w_await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "avgqu-sz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hdd",
     "select": [
      [
       { "params": [ "avgqu-sz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Received / Send data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Received" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Send" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received / Send packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Received packets" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Send packets" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received / Send errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_errs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Receive errors" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_errs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Send errors" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received / Send Dropped packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_host $tag_interface)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "receive_drop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Received dropped packets" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit_drop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Send dropped packets" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Database metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Nodes Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "database",
     "query": "SELECT last(\"node_state\") FROM \"database\" WHERE $timeFilter GROUP BY \"node_name\"",
     "select": [
      [
       { "params": [ "node_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries errors count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errors count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "database_history",
     "select": [
      [
       { "params": [ "error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries per label",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Request: $tag_request_label",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "request_label" ], "type": "tag" }
     ],
     "measurement": "database_history",
     "query": "SELECT mean(\"point_value\") FROM \"database_history\" WHERE (\"request_label\" != 'PERFORMANCE_AGENT' AND (\"request_duration_ms\" > 100 OR \"is_executing\" = true)) AND $timeFilter GROUP BY time(1m), \"request_label\"",
     "select": [
      [
       { "params": [ "point_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request_label", "operator": "!=", "value": "PERFORMANCE_AGENT" },
      { "condition": "AND", "key": "request_duration_ms", "operator": ">", "value": "100" },
      { "condition": "OR", "key": "is_executing", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Queries by Transaction ID",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_request_label ($tag_transaction_id | $tag_request_id)",
     "groupBy": [
      { "params": [ "1ms" ], "type": "time" },
      { "params": [ "transaction_id" ], "type": "tag" },
      { "params": [ "request_label" ], "type": "tag" },
      { "params": [ "request_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "database_history",
     "query": "SELECT count(\"point_type\") FROM \"database_history\" WHERE (\"request_label\" != 'PERFORMANCE_AGENT' AND ((\"is_executing\"=true AND \"request_duration_ms\" = 0)  OR \"request_duration_ms\" > 100)) AND $timeFilter GROUP BY time(1ms), \"transaction_id\", \"request_label\", \"request_id\" fill(none)",
     "select": [
      [
       { "params": [ "point_type" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "request_label", "operator": "!=", "value": "PERFORMANCE_AGENT" },
      { "condition": "AND", "key": "request_duration_ms", "operator": ">", "value": "100" },
      { "condition": "OR", "key": "is_executing", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Queries History",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "measurement": "database_history",
     "query": "SELECT \"transaction_id\", \"request_id\", \"request\", \"request_label\", \"request_duration_ms\",\"success\", \"is_executing\", \"error_count\" FROM \"database_history\" WHERE (\"point_type\" = 'start' AND \"request_label\" != 'PERFORMANCE_AGENT' AND ((\"is_executing\"=true  AND \"request_duration_ms\" = 0)  OR \"request_duration_ms\" > 100)) AND $timeFilter",
     "select": [
      [
       { "params": [ "transaction_id" ], "type": "field" }
      ],
      [
       { "params": [ "request_id" ], "type": "field" }
      ],
      [
       { "params": [ "request" ], "type": "field" }
      ],
      [
       { "params": [ "request_label" ], "type": "field" }
      ],
      [
       { "params": [ "request_duration_ms" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "is_executing" ], "type": "field" }
      ],
      [
       { "params": [ "error_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "point_type", "operator": "=", "value": "start" },
      { "condition": "AND", "key": "request_label", "operator": "!=", "value": "PERFORMANCE_AGENT" },
      { "condition": "AND", "key": "request_duration_ms", "operator": ">", "value": "100" }
     ]
    }
   ]
  },
  {
   "title": "Сluster request distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host | $tag_node_name",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}